name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Run prettier
        run: yarn run test:format

      - name: Run lint
        run: yarn run test:lint

      - name: Run tests
        run: yarn run test:unit
